# This file is a template, and might need editing before it works on your project.
# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/
image: m1kev4ndyke/docker-gtest

build:
  stage: build
  # instead of calling g++ directly you can also use some build toolkit like make
  # install the necessary build tools when needed
  before_script: 
    - apt update && apt -y install make autoconf cmake libgtest-dev lcov

  script:
    - mkdir mydns/build
    - cd mydns/build
    - cmake .. -DCOVERAGE=1
    - make -j
    - make test
    - ./test/runUnitTests
    - mkdir _coverage && cd _coverage
    - find .. -iname "*.gcda" | xargs gcov
    - lcov --capture --directory .. --output-file coverage.info
    - lcov --remove coverage.info '/usr/include/*' '/usr/lib/*' -o coverage_filtered.info
    - genhtml coverage_filtered.info --output-directory ../../../coverage
    - cd ../../..

  artifacts:
    paths:
      - coverage/

pages:
  stage: deploy
  dependencies:
    - build
  script:
    - mv coverage/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master
