repos:
- repo: git@github.com:pre-commit/pre-commit-hooks
  rev: v2.1.0
  hooks:
    # Disabled because yapf is better for our purpose
    # - id: autopep8-wrapper
    - id: check-added-large-files
    - id: debug-statements
    - id: double-quote-string-fixer
    - id: end-of-file-fixer
      exclude: 'static'
    - id: fix-encoding-pragma
      args: ['--remove']
    - id: check-merge-conflict
    - id: check-symlinks
    - id: trailing-whitespace
    - id: mixed-line-ending
      args: ['--fix=lf']
    - id: flake8
      additional_dependencies: [
      'flake8-blind-except',
      'flake8-commas',
      'flake8-comprehensions',
      'flake8-deprecated',
      'flake8-docstrings',
      'flake8-meiqia',
      'flake8-mutable',
      'flake8-pep3101',
      'flake8-quotes',
      'flake8-string-format',
      'flake8-tidy-imports',
      # These are good but are broken with current pydocstyle version
      # 'flake8-print',
      # 'flake8-debugger',
      # 'flake8-todo',
      ]
